name: WhoniverseEssentials
version: 1.0.0
author: xTheDoctah
main: eu.whoniverse.essentials.Main
commands:
  tp:
    description: Teleport!
    aliases: [teleport, tp]
    usage: /<command> [player]
  tphere:
    description: Teleport to u the player/s!
    aliases: [tphere,tph]
    usage: /<command> [player/s]